---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCbexkybE6bz27K1dQEPG3VQktW9XBFXfoTQV+sG/P17cmnBCXWeyD5gIvHWleJAz4oB+SdNHhl+/+TChRcG5aIbSC0Lnuu3An+jnbO9aDPcyiQuq3kJvLKWm1sRkWVpIvDYlTIjzAzFvmHKsXDiyo1sEdPIdpmYb6U57UJmvSdhaTyszE2B6PYdzUC8SD23sdAbWU/yJ6ULZaFapqtcd3lglRBYgo5lwKn6c8oQKiTgamB8sc+i8aEm9ktMoEg0lv+uaiSfo5Pk1KOZ0pS0c0kcvZEWuKbJo6YUrkPoNgMzTP0T3i258WwxxrCAcbg/astesLi0bwxssdn6Ls0+ggQ8QlmMkCSFcC2fV4wAFufsqMekXWa9JYZdhPvPN3q4WPLrTUV0sv3Fkej3+lOTTeHk2J2sb+emP4smYO8nOB3pTZNQAS3TVSHSHGMGW7sdgc5QYz+XSD3/8BRRbad48fjV8zO7Aa7Qe8hFsVwcTpaUE0f0Z4ELCnK0AfDBfyvOloq+WHWdNQBtAhHOUjBnlRwyXdwXl88cl13gmIeuTcUznm5KHzFrG9yHYxfwGsrBFLMpPp10JlNcsfcvKPje6Klsk2LpmlLkQsGqpHVZLBPkMTbEJy5xmLQFLYOC5aOPxUFQwZl/84STNUKyNa0TNbpGIcC0/xP0jFy69z+MOMZhNBCJggb7VhquJQT2C1T2eEI96MFaXgUeg==
    admin-user: AgAJB+4aqo9QIfwvke/zeHefyJV8XYyvemTX8CBQzfI7RybNqgzi0SQrbnveDXv+JcGjTlID++spe0DuOY2BWkXQ4cDV0Kp4victAuCXqcl+nIrUr3JyMto51aTFnI1X9VZT8iA0hCexiTQhX2GEWjty3BHl+cA0dyNaMtvCjy52T4u52+RNc2uKlQfMWUAXs6lnDfKao+Yyk6aX/eoCt/KPPMgeV7i5wD6xMx6fOq3i2rQAl9a8L9JitAsO+KyIeyhE+tiPUgg7aeSMDYmaxSn0kIVwgtJVaKsZfNkd039/g3fen6BpnZWB4Nv5Nr6XO/f+yaMINz+UbvlDvOPRK4rD2uwrPpnjPym7q/wotvGLbJq4Z5T9cGlK0P4zC0NtGmT8kCjFTCRJnIFjUEddum4X7fm1nc3s0VM7d1d38c7IBa4t4Tn+iqsCIDKOyI4WX05HbheHnnHiAHvTe7mn6Bqf7pJBHqOXjdrakWKeiG+rG/HVHziiSXkD+EV9v4nUzNuhjt1anOZuoS+5aU8xhGqPMOYNq336FFFgLNfikL1k/GBTZy/e3JRqNzDc0/u3Vvg3ozGfJTVkNEKlIFKOoTkNHMBS8dRnPnHGsKgX7Eognzz8WBVzjWOI9uDiX8AXoq4cfIhpZxxs2n92NxUjAuz6PROqCMVuZ2xoBzF9qWi0U68Tt60bcoIn5BpDgT05D8Gt5pD67Q==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
