apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: listmonk-app-resources
  namespace: monitoring
  labels:
    release: kps
spec:
  groups:
    - name: listmonk.app.resources
      rules:

        - alert: ListmonkHighCPU
          expr: |
            sum by (pod) (
              rate(container_cpu_usage_seconds_total{
                namespace="listmonk",
                pod=~"listmonk.*",
                container!="POD"
              }[5m])
            ) > 0.8
          for: 5m
          labels:
            severity: warning
            app: listmonk
          annotations:
            summary: "CPU alta en Listmonk"
            description: "El pod {{ $labels.pod }} usa >80% de una CPU"

        - alert: ListmonkHighMemory
          expr: |
            sum by (pod) (
              container_memory_working_set_bytes{
                namespace="listmonk",
                pod=~"listmonk.*",
                container!="POD"
              }
            )
            /
            sum by (pod) (
              kube_pod_container_resource_limits{
                namespace="listmonk",
                pod=~"listmonk.*",
                resource="memory"
              }
            ) > 0.9
          for: 5m
          labels:
            severity: warning
            app: listmonk
          annotations:
            summary: "Memoria alta en Listmonk"
            description: "El pod {{ $labels.pod }} usa >90% del límite de memoria"
