---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: listmonk-postgres
  namespace: monitoring
  labels:
    release: kps
spec:
  groups:
    - name: listmonk.postgres
      rules:

        - alert: ListmonkPostgresDown
          expr: |
            up{namespace="listmonk", pod=~"postgres.*"} == 0
          for: 1m
          labels:
            severity: critical
            app: listmonk
            component: postgres
          annotations:
            summary: "PostgreSQL no responde"
            description: "El pod de PostgreSQL está caído en listmonk"

        - alert: ListmonkPostgresHighMemory
          expr: |
            container_memory_working_set_bytes{
              namespace="listmonk",
              pod=~"postgres.*",
              container!="POD"
            } > 1e9
          for: 5m
          labels:
            severity: warning
            component: postgres
          annotations:
            summary: "Memoria alta en PostgreSQL"
            description: "Postgres usa >1GB de memoria"
