apiVersion: apps/v1
kind: Deployment
metadata:
  name: listmonk
  namespace: listmonk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: listmonk
  template:
    metadata:
      labels:
        app: listmonk
    spec:
      serviceAccountName: listmonk
      containers:
        - name: listmonk
          image: ghcr.io/ericnovales/listmonk_ericmod:v1.4.4
          ports:
            - containerPort: 9000
          command: ["sh", "-c"]
          args:
            - >
              ./listmonk --install --idempotent --yes --config '' &&
              ./listmonk --upgrade --yes --config '' &&
              ./listmonk --config ''
          env:
            - name: LISTMONK_app__address
              value: "0.0.0.0:9000"
            - name: LISTMONK_db__host
              value: "postgres"
            - name: LISTMONK_db__port
              value: "5432"
            - name: LISTMONK_db__user
              valueFrom:
                  secretKeyRef:
                    name: postgres-secret
                    key: POSTGRES_USER
            - name: LISTMONK_db__password
              valueFrom:
                  secretKeyRef:
                    name: postgres-secret
                    key: POSTGRES_PASSWORD
            - name: LISTMONK_db__database
              valueFrom:
                  secretKeyRef:
                    name: postgres-secret
                    key: POSTGRES_DB
            - name: LISTMONK_db__ssl_mode
              value: "disable"
            - name: TZ
              value: "Etc/UTC"
          volumeMounts:
            - name: uploads
              mountPath: /listmonk/uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: listmonk-uploads-pvc

