apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpit
  namespace: mail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailpit
  template:
    metadata:
      labels:
        app: mailpit
    spec:
      serviceAccountName: mailpit
      containers:
        - name: mailpit
          image: axllent/mailpit:latest
          ports:
            - name: smtp
              containerPort: 1025
            - name: http
              containerPort: 8025
