---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: listmonk-http
  namespace: monitoring
  labels:
    release: kps
spec:
  groups:
    - name: listmonk.app.http
      rules:

        - alert: ListmonkHighLatency
          expr: |
            histogram_quantile(
              0.95,
              sum by (le) (
                rate(http_request_duration_seconds_bucket{
                  namespace="listmonk",
                  pod=~"listmonk.*"
                }[5m])
              )
            ) > 1
          for: 3m
          labels:
            severity: warning
            app: listmonk
          annotations:
            summary: "Latencia HTTP alta en Listmonk"
            description: "p95 de latencia >1s durante 3 minutos"

        - alert: ListmonkHttp5xx
          expr: |
            sum(rate(http_requests_total{
              namespace="listmonk",
              pod=~"listmonk.*",
              status=~"5.."
            }[5m]))
            /
            sum(rate(http_requests_total{
              namespace="listmonk",
              pod=~"listmonk.*"
            }[5m]))
            > 0.05
          for: 2m
          labels:
            severity: critical
            app: listmonk
          annotations:
            summary: "Errores 5xx en Listmonk"
            description: "Más del 5% de requests devuelven 5xx"

