apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-analysis-to-listmonk-and-dns
  namespace: listmonk
spec:
  podSelector:
    matchLabels:
      role: analysis
  policyTypes:
    - Egress
  egress:
    # HTTP hacia listmonk (pods)
    - to:
        - podSelector:
            matchLabels:
              app: listmonk
      ports:
        - protocol: TCP
          port: 9000
